from rest_framework import serializers
from .models import TaskCategory

class CategorySerializer(serializers.ModelSerializer):
    """
    Serializer for the TaskCategory model.

    This serializer handles the validation and serialization of task categories.
    """
    class Meta:
        model = TaskCategory  # Specify the model to be serialized
        fields = ['id', 'name']  # Specify fields to include in the serialization
        read_only_fields = ['id']  # Mark 'id' as read-only since it's auto-generated by the database

    def create(self, validated_data):
        """
        Create and return a new TaskCategory instance, given the validated data.

        Args:
            validated_data (dict): The validated data for creating a TaskCategory.

        Returns:
            TaskCategory: The newly created TaskCategory instance.
        """
        # Create a new TaskCategory instance with validated data
        category = TaskCategory.objects.create(**validated_data)
        return category
