# Generated by Django 5.1 on 2024-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Fitness', 'Fitness'), ('Education', 'Education'), ('Fitness', 'Finances'), ('Miscellaneous', 'Miscellaneous')], max_length=100, unique=True),
        ),
    ]
